package cl.dynasty.nexusbeacon.platform.classic;
import static org.junit.jupiter.api.Assertions.*;import java.util.ArrayList;import java.util.Collection;import java.util.Collections;import java.util.List;import java.util.UUID;import org.bukkit.Particle;import org.junit.jupiter.api.Test;
class ClassicVisualRuntimeTest {
 @Test void configuredNinetySixPointsProduceExactlyNinetySixTerrainAwareSamples(){Fixture f=new Fixture(record(70),96);f.world.terrain=72;f.runtime.tick();assertEquals(96,f.emitter.points.size());for(ClassicVisualRuntime.Point p:f.emitter.points)assertEquals(92.5D,p.y,.001D);}
 @Test void configuredPointCountIsAuthoritativeAndInvalidValuesUseSafeMinimum(){Fixture configured=new Fixture(record(70),32);configured.runtime.tick();assertEquals(32,configured.emitter.points.size());Fixture invalid=new Fixture(record(70),0);invalid.runtime.tick();assertEquals(8,invalid.emitter.points.size());assertEquals(8,ClassicVisualRuntime.safeRadiusPoints(-5));}
 @Test void undergroundUsesSurfaceAndHighBeaconWins(){Fixture underground=new Fixture(record(-40),96);underground.world.terrain=65;underground.runtime.tick();assertEquals(85.5D,underground.emitter.points.get(0).y,.001D);Fixture mountain=new Fixture(record(180),96);mountain.world.terrain=150;mountain.world.max=255;mountain.runtime.tick();assertEquals(200.5D,mountain.emitter.points.get(0).y,.001D);}
 @Test void localTerrainAndWorldCeilingAreAppliedPerSample(){Fixture f=new Fixture(record(100),96);f.world.variable=true;f.world.max=150;f.runtime.tick();boolean low=false,ceiling=false;for(ClassicVisualRuntime.Point p:f.emitter.points){low|=p.y==120.5D;ceiling|=p.y==150.5D;}assertTrue(low);assertTrue(ceiling);}
 @Test void unloadedChunksAreSkippedAndTerrainQueriesAreCached(){Fixture f=new Fixture(record(70),96);f.world.loaded=false;f.runtime.tick();assertEquals(0,f.emitter.points.size());assertEquals(0,f.world.queries);f.world.loaded=true;for(int i=0;i<19;i++)f.runtime.tick();assertEquals(0,f.emitter.points.size());f.runtime.tick();assertEquals(96,f.emitter.points.size());int queries=f.world.queries;f.runtime.tick();assertEquals(queries,f.world.queries);}
 private static ClassicBeaconRecord record(int y){return new ClassicBeaconRecord(new ClassicBeaconLocation("world",0,y,0),UUID.randomUUID(),UUID.randomUUID(),48,1,Collections.<String,Integer>emptyMap(),Collections.<String>emptySet(),Collections.<UUID>emptySet(),true,null,true,"FLAME");}
 private static final class Fixture{final ClassicBeaconRecord record;final FakeWorld world=new FakeWorld();final FakeEmitter emitter=new FakeEmitter();final ClassicVisualRuntime runtime;Fixture(ClassicBeaconRecord r,int points){record=r;runtime=new ClassicVisualRuntime(new ClassicVisualRuntime.Records(){public Collection<ClassicBeaconRecord> snapshot(){return Collections.singleton(record);}},new ClassicParticleResolver(),world,emitter,points);}}
 private static final class FakeWorld implements ClassicVisualRuntime.WorldView{boolean loaded=true,variable;int terrain=70,min=0,max=255,queries;public boolean beaconPresent(ClassicBeaconRecord r){return true;}public boolean chunkLoaded(ClassicBeaconRecord r,int x,int z){return loaded;}public int highestY(ClassicBeaconRecord r,int x,int z){queries++;return variable?(x>=0?140:100):terrain;}public int minY(ClassicBeaconRecord r){return min;}public int maxY(ClassicBeaconRecord r){return max;}}
 private static final class FakeEmitter implements ClassicVisualRuntime.Emitter{final List<ClassicVisualRuntime.Point> points=new ArrayList<ClassicVisualRuntime.Point>();public void emit(ClassicBeaconRecord r,Particle particle,double x,double y,double z){points.add(new ClassicVisualRuntime.Point(x,y,z));}}
}
