package cl.dynasty.nexusbeacon.platform.classic;
import static org.junit.jupiter.api.Assertions.*;import java.util.HashMap;import java.util.Map;import java.util.Random;import org.junit.jupiter.api.Test;
class ClassicEffectRuntimeTest {
 @Test void normalPotionLevelsUseBukkitZeroBasedAmplifiers(){assertEquals(0,ClassicEffectRuntime.potionAmplifier(1,1));assertEquals(2,ClassicEffectRuntime.potionAmplifier(3,1));}
 @Test void cropWorkLimitsFailClosedAndStayBounded(){assertEquals(0,ClassicEffectRuntime.boundedWork(-1));assertEquals(16,ClassicEffectRuntime.boundedWork(16));assertEquals(2500,ClassicEffectRuntime.boundedWork(2500));}
 @Test void spawnerBaseComesFromMinMaxNotRemainingDelay(){Random fixed=new Random(){public int nextInt(int bound){return bound-1;}};assertEquals(799,ClassicEffectRuntime.randomizedBaseDelay(200,800,fixed));}
 @Test void spawnerPercentageAndLevelCooldownAreApplied(){assertEquals(720,ClassicEffectRuntime.boostedSpawnerDelay(800,10));assertEquals(400,ClassicEffectRuntime.boostedSpawnerDelay(800,50));assertEquals(8000L,ClassicEffectRuntime.cooldownMillis(160));assertEquals(4000L,ClassicEffectRuntime.cooldownMillis(80));}
 @Test void spawnerMetaConflictIsOptionalAndFailClosed(){assertTrue(ClassicEffectRuntime.spawnerConflict(true,true));assertFalse(ClassicEffectRuntime.spawnerConflict(false,true));assertFalse(ClassicEffectRuntime.spawnerConflict(true,false));}
 @Test void worldBoundsAcceptNegativeYOnlyWhenRuntimeMinimumAllowsIt(){assertEquals(0,ClassicWorldHeightCompatibility.minimumHeight(new OldWorld()));assertEquals(-64,ClassicWorldHeightCompatibility.minimumHeight(new NegativeWorld()));assertTrue(ClassicWorldHeightCompatibility.validY(-20,-64,320));assertTrue(ClassicWorldHeightCompatibility.validY(-64,-64,320));assertFalse(ClassicWorldHeightCompatibility.validY(-65,-64,320));assertTrue(ClassicWorldHeightCompatibility.validY(0,-64,320));assertFalse(ClassicWorldHeightCompatibility.validY(320,-64,320));assertFalse(ClassicWorldHeightCompatibility.validY(-20,0,256));}
 @Test void cropAndSpawnerAcceptValidNegativeYAndPreserveOldWorldBoundary(){assertTrue(ClassicEffectRuntime.cropYValid(-20,-64,320));assertTrue(ClassicEffectRuntime.spawnerYValid(-20,-64,320));assertFalse(ClassicEffectRuntime.cropYValid(-20,0,256));assertFalse(ClassicEffectRuntime.spawnerYValid(-20,0,256));}
 @Test void spawnerCountdownIsReducedOnceThenAllowedToDecreaseNaturally(){ClassicSpawnerCountdown.State state=new ClassicSpawnerCountdown.State();Random high=highRandom();assertEquals(400,observe(state,700,1,0));assertEquals(360,observe(state,360,2,2000));assertEquals(320,observe(state,320,3,4000));assertEquals(320,observe(state,320,4,6000));}
 @Test void spawnerNewCycleCanBeBoostedWithoutEverIncreasingCurrentDelay(){ClassicSpawnerCountdown.State state=new ClassicSpawnerCountdown.State();assertEquals(400,observe(state,700,1,0));assertEquals(20,observe(state,20,2,2000));assertEquals(760,observe(state,760,3,3000));assertEquals(400,observe(state,720,4,4000));assertEquals(150,observe(new ClassicSpawnerCountdown.State(),150,1,0));}
 @Test void spawnerCycleStateCleanupIsDeterministic(){Map<String,ClassicSpawnerCountdown.State> states=new HashMap<String,ClassicSpawnerCountdown.State>();ClassicSpawnerCountdown.State state=new ClassicSpawnerCountdown.State();states.put("world;0;-20;0",state);observe(state,400,1,0);ClassicSpawnerCountdown.clean(states,301);assertEquals(1,states.size());ClassicSpawnerCountdown.clean(states,302);assertTrue(states.isEmpty());}
 @Test void entityQueryCoversFullRuntimeHeightWithoutChangingHorizontalCircle(){assertEquals(313D,ClassicEffectRuntime.entityVerticalRadius(-57D,0,256));assertEquals(377D,ClassicEffectRuntime.entityVerticalRadius(-57D,-64,320));assertTrue(ClassicEffectRuntime.insideHorizontal(0D,0D,48));assertTrue(ClassicEffectRuntime.insideHorizontal(48D,0D,48));assertTrue(ClassicEffectRuntime.insideHorizontal(0D,48D,48));assertFalse(ClassicEffectRuntime.insideHorizontal(48D,1D,48));assertFalse(ClassicEffectRuntime.insideHorizontal(49D,0D,48));}
 @Test void allAndOnlyEntityExecutorsUseTheWorldHeightQuery(){assertTrue(ClassicEffectRuntime.usesSharedEntityQuery("POTION"));assertTrue(ClassicEffectRuntime.usesSharedEntityQuery("IGNITION"));assertTrue(ClassicEffectRuntime.usesSharedEntityQuery("DAMAGE_FIELD"));assertTrue(ClassicEffectRuntime.usesSharedEntityQuery("GRAVITY_PULSE"));assertFalse(ClassicEffectRuntime.usesSharedEntityQuery("CROP_BOOST"));assertFalse(ClassicEffectRuntime.usesSharedEntityQuery("SPAWNER_BOOST"));assertFalse(ClassicEffectRuntime.usesSharedEntityQuery("BLOCK_PROCESS_BOOST"));}
 @Test void configuredBlockScannerVerticalRadiiRemainBounded(){assertEquals(8,ClassicEffectRuntime.boundedWork(8));assertEquals(16,ClassicEffectRuntime.boundedWork(16));assertTrue(ClassicEffectRuntime.cropYValid(-20,-64,320));assertTrue(ClassicEffectRuntime.spawnerYValid(-20,-64,320));}
 public static final class OldWorld{}
 public static final class NegativeWorld{public int getMinHeight(){return -64;}}
 private static Random highRandom(){return new Random(){public int nextInt(int bound){return bound-1;}};}
 private static int observe(ClassicSpawnerCountdown.State state,int current,long scan,long now){return ClassicSpawnerCountdown.observe(state,current,200,800,50D,highRandom(),scan,now,4000L);}
}
