package cl.dynasty.nexusbeacon.platform.classic;
import static org.junit.jupiter.api.Assertions.*;import java.util.ArrayList;import java.util.Collection;import java.util.Collections;import java.util.LinkedHashMap;import java.util.List;import java.util.Map;import java.util.UUID;import org.bukkit.Particle;import org.junit.jupiter.api.BeforeEach;import org.junit.jupiter.api.Test;
class ClassicGuiMutationServiceTest {
 private static final ClassicBeaconLocation LOCATION=new ClassicBeaconLocation("world",4,70,9);private ClassicApplicationState state;private ClassicGuiMutationService mutations;
 @BeforeEach void setUp(){state=new ClassicApplicationState(new Memory());state.initialize();state.insert(new ClassicBeaconRecord(LOCATION,UUID.randomUUID(),UUID.randomUUID(),48,1,Collections.<String,Integer>emptyMap(),Collections.<String>emptySet(),Collections.<UUID>emptySet(),true,null,true,"VILLAGER_HAPPY"));Map<String,ClassicBeamStyle> styles=new LinkedHashMap<String,ClassicBeamStyle>();styles.put("aqua",new ClassicBeamStyle("aqua",Particle.REDSTONE,null,1.0F,false));styles.put("end_rod",new ClassicBeamStyle("end_rod",Particle.END_ROD,null,1.0F,false));mutations=new ClassicGuiMutationService(state,styles);}
 @Test void actionableRangeControlPersistsIndependentOfBeam(){assertEquals(ClassicGuiMutationService.Result.COMMITTED,mutations.toggleRange(LOCATION));assertFalse(state.find(LOCATION).isRangeParticles());assertNull(state.find(LOCATION).getBeamStyle());}
 @Test void availableBeamStyleSelectionPersistsIndependentOfRange(){assertEquals(ClassicGuiMutationService.Result.COMMITTED,mutations.selectBeam(LOCATION,"aqua"));assertEquals("aqua",state.find(LOCATION).getBeamStyle());assertTrue(state.find(LOCATION).isRangeParticles());}
 @Test void unsupportedBeamStyleCannotBeSelected(){assertEquals(ClassicGuiMutationService.Result.UNSUPPORTED,mutations.selectBeam(LOCATION,"unsupported"));assertNull(state.find(LOCATION).getBeamStyle());}
 @Test void absentExecutorCannotActivateOrGrantEffect(){assertEquals(ClassicGuiMutationService.Result.EXECUTOR_UNAVAILABLE,mutations.activateEffect(LOCATION,"speed"));assertTrue(state.find(LOCATION).getEffects().isEmpty());assertTrue(state.find(LOCATION).getActiveEffects().isEmpty());}
 static final class Memory implements ClassicBeaconStorage {private List<ClassicBeaconRecord> values=new ArrayList<ClassicBeaconRecord>();public ClassicStorageLoad load(){return ClassicStorageLoad.success(values);}public void store(Collection<ClassicBeaconRecord> records){values=new ArrayList<ClassicBeaconRecord>(records);}public void close(){}}
}
