package cl.dynasty.nexusbeacon.platform.classic;
import static org.junit.jupiter.api.Assertions.*;import java.lang.reflect.Proxy;import java.util.Collections;import java.util.UUID;import org.bukkit.World;import org.bukkit.block.Block;import org.bukkit.entity.Player;import org.junit.jupiter.api.Test;
class ClassicBaseProtectionListenerTest {
 @Test void exactManagedBaseIsProtectedButNearbyMineralIsNot(){ClassicApplicationState state=new ClassicApplicationState(new ClassicApplicationStateTest.Memory());state.initialize();ClassicBeaconRecord record=new ClassicBeaconRecord(new ClassicBeaconLocation("world",0,64,0),UUID.randomUUID(),UUID.randomUUID(),48,1,Collections.<String,Integer>emptyMap(),Collections.<String>emptySet(),Collections.<UUID>emptySet(),true,null,true,"FLAME");state.insert(record);ClassicBaseProtectionListener listener=new ClassicBaseProtectionListener(state,true,true,4);assertEquals(record,listener.find(block(1,63,1)));assertNull(listener.find(block(2,63,0)));}
 @Test void ownerTrustedAndAdminAreAllowedButStrangerIsNot(){UUID owner=UUID.randomUUID(),trusted=UUID.randomUUID();ClassicBeaconRecord record=new ClassicBeaconRecord(new ClassicBeaconLocation("world",0,64,0),UUID.randomUUID(),owner,48,1,Collections.<String,Integer>emptyMap(),Collections.<String>emptySet(),Collections.singleton(trusted),true,null,true,"FLAME");assertTrue(ClassicBaseProtectionListener.authorized(player(owner,false),record));assertTrue(ClassicBaseProtectionListener.authorized(player(trusted,false),record));assertTrue(ClassicBaseProtectionListener.authorized(player(UUID.randomUUID(),true),record));assertFalse(ClassicBaseProtectionListener.authorized(player(UUID.randomUUID(),false),record));}
 private static Block block(final int x,final int y,final int z){final World world=(World)Proxy.newProxyInstance(World.class.getClassLoader(),new Class<?>[]{World.class},(p,m,a)->m.getName().equals("getName")?"world":defaultValue(m.getReturnType()));return (Block)Proxy.newProxyInstance(Block.class.getClassLoader(),new Class<?>[]{Block.class},(p,m,a)->m.getName().equals("getWorld")?world:m.getName().equals("getX")?x:m.getName().equals("getY")?y:m.getName().equals("getZ")?z:defaultValue(m.getReturnType()));}
 private static Player player(final UUID id,final boolean admin){return (Player)Proxy.newProxyInstance(Player.class.getClassLoader(),new Class<?>[]{Player.class},(p,m,a)->m.getName().equals("getUniqueId")?id:m.getName().equals("hasPermission")?admin:defaultValue(m.getReturnType()));}
 private static Object defaultValue(Class<?> type){if(type==boolean.class)return false;if(type==int.class)return 0;if(type==long.class)return 0L;if(type==double.class)return 0D;if(type==float.class)return 0F;if(type==short.class)return (short)0;if(type==byte.class)return (byte)0;if(type==char.class)return (char)0;return null;}
}
