package cl.dynasty.nexusbeacon.platform.classic;
import static org.junit.jupiter.api.Assertions.*;import java.lang.reflect.Proxy;import java.util.ArrayList;import java.util.Collection;import java.util.Collections;import java.util.List;import java.util.UUID;import java.util.logging.Logger;import org.bukkit.configuration.file.YamlConfiguration;import org.bukkit.entity.Player;import org.bukkit.potion.PotionEffectType;import org.junit.jupiter.api.BeforeEach;import org.junit.jupiter.api.Test;
class ClassicPurchaseServiceTest {private final UUID owner=UUID.randomUUID(),beaconId=UUID.randomUUID();private Memory storage;private ClassicApplicationState state;private FakeEconomy economy;private ClassicPurchaseService service;private Player player;
 @BeforeEach void setUp(){YamlConfiguration config=new YamlConfiguration();config.set("effects.speed.enabled",true);config.set("effects.speed.type","POTION");config.set("effects.speed.potion","SPEED");config.set("effects.speed.icon","DIAMOND_BOOTS");config.set("effects.speed.max-level",3);price(config,"acquire",500D);price(config,"upgrade",600D);ClassicEffectCatalog catalog=new ClassicEffectCatalog(config.getConfigurationSection("effects"),new ClassicMaterialResolver(),new ClassicPotionEffectResolver(n->PotionEffectType.SPEED));storage=new Memory();state=new ClassicApplicationState(storage);state.initialize();state.insert(new ClassicBeaconRecord(new ClassicBeaconLocation("world",1,64,2),beaconId,owner,48,1,Collections.<String,Integer>emptyMap(),Collections.<String>emptySet(),Collections.<UUID>emptySet(),true,null,true,"FLAME"));economy=new FakeEconomy();service=new ClassicPurchaseService(state,catalog,config,economy,Logger.getAnonymousLogger());player=player(owner);}
 @Test void successfulPurchaseChargesOnceAndPublishesPersistedOwnership(){economy.balance=1000;assertEquals(ClassicPurchaseService.Result.COMMITTED,service.purchase(player,beaconId,"speed","money"));assertEquals(1,economy.withdrawals);assertEquals(Integer.valueOf(1),state.findByUniqueId(beaconId).getEffects().get("speed"));assertTrue(state.findByUniqueId(beaconId).getActiveEffects().contains("speed"));}
 @Test void insufficientFundsAndWithdrawalFailureGrantNothing(){economy.balance=1;assertEquals(ClassicPurchaseService.Result.INSUFFICIENT_FUNDS,service.purchase(player,beaconId,"speed","money"));assertTrue(state.findByUniqueId(beaconId).getEffects().isEmpty());economy.balance=1000;economy.withdrawSucceeds=false;assertEquals(ClassicPurchaseService.Result.DEBIT_FAILED,service.purchase(player,beaconId,"speed","money"));assertTrue(state.findByUniqueId(beaconId).getEffects().isEmpty());}
 @Test void upgradeUsesNextLevelAndChargesOnce(){economy.balance=2000;assertEquals(ClassicPurchaseService.Result.COMMITTED,service.purchase(player,beaconId,"speed","money"));economy.withdrawals=0;assertEquals(ClassicPurchaseService.Result.COMMITTED,service.purchase(player,beaconId,"speed","money"));assertEquals(1,economy.withdrawals);assertEquals(Integer.valueOf(2),state.findByUniqueId(beaconId).getEffects().get("speed"));}
 @Test void persistenceFailureRefundsAndNeverPublishes(){economy.balance=1000;storage.fail=true;assertEquals(ClassicPurchaseService.Result.PERSISTENCE_FAILED_REFUNDED,service.purchase(player,beaconId,"speed","money"));assertEquals(1,economy.deposits);assertTrue(state.findByUniqueId(beaconId).getEffects().isEmpty());}
 @Test void absentEconomyFailsClosed(){economy.available=false;assertEquals(ClassicPurchaseService.Result.ECONOMY_UNAVAILABLE,service.purchase(player,beaconId,"speed","money"));assertTrue(state.findByUniqueId(beaconId).getEffects().isEmpty());}
 private static void price(YamlConfiguration c,String action,double amount){c.set("effects.speed.costs."+action+".options.money.type","VAULT_MONEY");c.set("effects.speed.costs."+action+".options.money.amount",amount);}
 private static Player player(final UUID id){return (Player)Proxy.newProxyInstance(Player.class.getClassLoader(),new Class<?>[]{Player.class},(p,m,a)->{if(m.getName().equals("getUniqueId"))return id;if(m.getName().equals("hasPermission"))return false;Class<?> t=m.getReturnType();if(t==boolean.class)return false;if(t==int.class)return 0;if(t==double.class)return 0D;if(t==float.class)return 0F;if(t==long.class)return 0L;return null;});}
 static final class FakeEconomy implements ClassicEconomyService{boolean available=true,withdrawSucceeds=true;double balance;int withdrawals,deposits;public boolean isAvailable(){return available;}public boolean has(Player p,double a){return balance>=a;}public boolean withdraw(Player p,double a){withdrawals++;if(!withdrawSucceeds)return false;balance-=a;return true;}public boolean deposit(Player p,double a){deposits++;balance+=a;return true;}public String diagnostic(){return available?"available":"absent";}}
 static final class Memory implements ClassicBeaconStorage{List<ClassicBeaconRecord> values=new ArrayList<ClassicBeaconRecord>();boolean fail;public ClassicStorageLoad load(){return ClassicStorageLoad.success(values);}public void store(Collection<ClassicBeaconRecord> records){if(fail)throw new ClassicStorageException("fail");values=new ArrayList<ClassicBeaconRecord>(records);}public void close(){}}
}
