package cl.dynasty.nexusbeacon.platform.classic;
import static org.junit.jupiter.api.Assertions.*;import java.util.Collections;import java.util.UUID;import org.bukkit.Material;import org.bukkit.inventory.ItemStack;import org.junit.jupiter.api.BeforeEach;import org.junit.jupiter.api.Test;import cl.dynasty.nexusbeacon.platform.api.*;
class ClassicBeaconTransactionsTest {private ClassicApplicationState state;private ClassicBeaconTransactions tx;private final ClassicBeaconLocation location=new ClassicBeaconLocation("world",1,64,1);private final ItemStack marked=new ItemStack(Material.BEACON);
 @BeforeEach void setup(){state=new ClassicApplicationState(new ClassicApplicationStateTest.Memory());state.initialize();tx=new ClassicBeaconTransactions(state,new FakeIdentity(),48,true,true,"FLAME");}
 @Test void onlyCanonicalItemPlacesExactlyOnce(){assertTrue(tx.place(marked,location,UUID.randomUUID(),false).isCommitted());assertEquals(1,state.size());assertEquals(ClassicBeaconTransactions.Status.DUPLICATE,tx.place(marked,location,UUID.randomUUID(),false).getStatus());}
 @Test void ordinaryBeaconAndCancellationNeverPublish(){assertEquals(ClassicBeaconTransactions.Status.UNMARKED,tx.place(new ItemStack(Material.STONE),location,UUID.randomUUID(),false).getStatus());assertEquals(ClassicBeaconTransactions.Status.CANCELLED,tx.place(marked,location,UUID.randomUUID(),true).getStatus());assertEquals(0,state.size());}
 @Test void exactRemovalAndCancellation(){tx.place(marked,location,UUID.randomUUID(),false);assertEquals(ClassicBeaconTransactions.Status.CANCELLED,tx.remove(location,true).getStatus());assertEquals(1,state.size());assertTrue(tx.remove(location,false).isCommitted());assertEquals(ClassicBeaconTransactions.Status.UNMANAGED,tx.remove(location,false).getStatus());}
 @Test void failedStorageDeletionFailsClosedAndKeepsAuthoritativeState(){ClassicApplicationStateTest.Memory storage=new ClassicApplicationStateTest.Memory();state=new ClassicApplicationState(storage);state.initialize();tx=new ClassicBeaconTransactions(state,new FakeIdentity(),48,true,true,"FLAME");assertTrue(tx.place(marked,location,UUID.randomUUID(),false).isCommitted());storage.fail=true;assertEquals(ClassicBeaconTransactions.Status.STORAGE_FAILURE,tx.remove(location,false).getStatus());assertEquals(1,state.size());}
 static final class FakeIdentity implements ItemIdentityService {public IdentificationResult identify(ItemStack i){return i!=null&&i.getType()==Material.BEACON?IdentificationResult.recognized(ItemIdentity.NEXUS_BEACON,IdentificationResult.Evidence.PERSISTENT_MARKER):IdentificationResult.notRecognized();}public ItemStack mark(ItemStack i,ItemIdentity x){return i.clone();}}
}
