package cl.dynasty.nexusbeacon.platform.classic;
import static org.junit.jupiter.api.Assertions.*;import java.util.ArrayList;import java.util.Collection;import java.util.Collections;import java.util.List;import java.util.UUID;import org.junit.jupiter.api.Test;
class ClassicApplicationStateTest {private static final ClassicBeaconLocation L=new ClassicBeaconLocation("world",1,64,2);private static ClassicBeaconRecord record(){return new ClassicBeaconRecord(L,UUID.randomUUID(),UUID.randomUUID(),48,1,Collections.<String,Integer>emptyMap(),Collections.<String>emptySet(),Collections.<UUID>emptySet(),true,null,true,"FLAME");}
 @Test void emptyLoadIsAuthoritative(){ClassicApplicationState s=new ClassicApplicationState(new Memory());assertTrue(s.initialize().isSuccessful());assertEquals(0,s.size());assertEquals(ClassicApplicationState.Status.READY_EMPTY,s.getStatus());}
 @Test void saveUpdateRemoveArePersistBeforePublish(){Memory m=new Memory();ClassicApplicationState s=new ClassicApplicationState(m);s.initialize();ClassicBeaconRecord r=record();assertTrue(s.insert(r));assertEquals(1,m.values.size());assertTrue(s.update(r.withVisuals("red",false,"FLAME")));assertEquals("red",s.find(L).getBeamStyle());assertEquals(r.getUniqueId(),s.remove(L).getUniqueId());assertEquals(0,s.size());}
 @Test void failedPersistenceDoesNotPublish(){Memory m=new Memory();ClassicApplicationState s=new ClassicApplicationState(m);s.initialize();m.fail=true;assertThrows(ClassicStorageException.class,()->s.insert(record()));assertEquals(0,s.size());}
 @Test void loadFailureNeverPublishes(){ClassicApplicationState s=new ClassicApplicationState(new Memory(true));assertFalse(s.initialize().isSuccessful());assertEquals(ClassicApplicationState.Status.FAILED,s.getStatus());assertThrows(IllegalStateException.class,()->s.size());}
 static final class Memory implements ClassicBeaconStorage {List<ClassicBeaconRecord>values=new ArrayList<ClassicBeaconRecord>();boolean fail;Memory(){}Memory(boolean f){fail=f;}public ClassicStorageLoad load(){return fail?ClassicStorageLoad.failure(ClassicStorageLoad.Status.UNAVAILABLE,"fail"):ClassicStorageLoad.success(values);}public void store(Collection<ClassicBeaconRecord> r){if(fail)throw new ClassicStorageException("fail");values=new ArrayList<ClassicBeaconRecord>(r);}public void close(){}}
}
