# ============================================================
# ALMACENAMIENTO
# ============================================================
# Define dónde se guardarán los datos de NexusBeacon.
#
# Tipos disponibles:
# - YAML   : Guarda datos en plugins/NexusBeacon/storage.yml
# - MYSQL  : Guarda datos en una base de datos MySQL/MariaDB
# - SQLITE : Guarda datos en un archivo local SQLite
#
# Recomendado:
# - YAML para servidores pequeños o pruebas.
# - SQLITE para uso local más ordenado sin configurar base externa.
# - MYSQL para redes, servidores grandes o sincronización externa.
# ============================================================
# Idioma principal del plugin.
# Debe existir en plugins/NexusBeacon/languages/<idioma>.yml

language: es_cl

debug: false

settings:
  require-permission: true
  permission-use: NexusBeacon.use
  shift-click-menu: true

gui:
  refresh-ticks: 20
  sounds: true

storage:
  type: YAML

  mysql:
    host: localhost
    port: 3306
    database: NexusBeacon
    username: root
    password: ""
    use-ssl: false
    table-prefix: NexusBeacon_

  sqlite:
    file: storage.db
