name: DynaBeacon
version: 4.3.3
main: cl.dynasty.dynabeacon.DynaBeaconPlugin
author: Karuho
description: Sistema propio de beacons avanzados para Dynacraft.
softdepend: [Vault, SpawnerMeta, Towny, WorldGuard, PlotSquared, GriefPrevention, WorldEdit]

commands:
  dynabeacon:
    description: Comando principal de DynaBeacon.
    usage: /dynabeacon
    aliases: [dbeacon, beacon, dynab]

permissions:
  dynabeacon.admin:
    default: op
  dynabeacon.use:
    default: true