name: NexusBeacon
version: 4.5.0
main: cl.dynasty.nexusbeacon.NexusBeaconPlugin
api-version: '1.21'
author: Karuho
description: Sistema de beacon con efectos personalizables, menús y opciones de pago.
softdepend: [Vault, PlaceholderAPI, SpawnerMeta, Towny, WorldGuard, PlotSquared, GriefPrevention, WorldEdit]
folia-supported: true

commands:
  NexusBeacon:
    description: Comando principal de NexusBeacon.
    usage: /NexusBeacon
    aliases: [nbeacon, beacon, nb, nbe]

permissions:
  NexusBeacon.admin:
    default: op
  NexusBeacon.use:
    default: true