# ============================================================
# STORAGE
# ============================================================
# Defines where NexusBeacon data will be stored.
#
# Available types:
# - YAML   : Stores data in plugins/NexusBeacon/storage.yml
# - MYSQL  : Stores data in a MySQL/MariaDB database
# - SQLITE : Stores data in a local SQLite file
#
# Recommended:
# - YAML for small servers or testing.
# - SQLITE for cleaner local storage without external database setup.
# - MYSQL for networks, large servers, or external synchronization.
# ============================================================

# Main plugin language.
# The selected language file must exist in:
# plugins/NexusBeacon/languages/<language>.yml
#
# NexusBeacon currently provides:
# - en_us.yml (default)
# - es_cl.yml
#
# You may create your own language files by following
# the same naming format:
# <language>_<country>.yml
#
# Examples:
# - en_us.yml
# - es_cl.yml
# - es_mx.yml
# - fr_fr.yml

language: en_us

debug: false
 
settings:
  require-permission: true
  permission-use: NexusBeacon.use
  shift-click-menu: true

gui:
  refresh-ticks: 20
  sounds: true

storage:
  type: YAML

  mysql:
    host: localhost
    port: 3306
    database: NexusBeacon
    username: root
    password: ""
    use-ssl: false
    table-prefix: NexusBeacon_

  sqlite:
    file: storage.db
