name: NexusBeacon
version: 1.2.5
main: cl.dynasty.nexusbeacon.NexusBeaconPlugin
api-version: '1.21'
author: DynaDev
softdepend: [Vault, PlaceholderAPI, SpawnerMeta]
folia-supported: true

commands:
  NexusBeacon:
    description: Comando principal de NexusBeacon.
    usage: /NexusBeacon
    aliases: [nbeacon, beacon, nb, nbe]

permissions:
  NexusBeacon.admin:
    default: op
  NexusBeacon.use:
    default: true