package cl.dynasty.nexusbeacon.platform.classic;

import java.io.File; import java.io.IOException; import java.nio.charset.StandardCharsets; import java.nio.file.Files; import java.nio.file.Path; import java.nio.file.StandardCopyOption;
import java.util.ArrayList; import java.util.Collection; import java.util.HashSet; import java.util.List; import java.util.Map; import java.util.Set; import java.util.TreeMap; import java.util.UUID;
import org.bukkit.configuration.ConfigurationSection; import org.bukkit.configuration.InvalidConfigurationException; import org.bukkit.configuration.file.YamlConfiguration;

public final class ClassicYamlBeaconStorage implements ClassicBeaconStorage {
    private final File file;
    public ClassicYamlBeaconStorage(File file){if(file==null)throw new NullPointerException("file");this.file=file;}
    public ClassicStorageLoad load(){if(!file.exists())return ClassicStorageLoad.success(new ArrayList<ClassicBeaconRecord>());if(!file.isFile())return ClassicStorageLoad.failure(ClassicStorageLoad.Status.UNAVAILABLE,"Storage is not a file");
        YamlConfiguration y=new YamlConfiguration();try{y.load(file);ConfigurationSection root=y.getConfigurationSection("beacons");if(root==null)return ClassicStorageLoad.failure(ClassicStorageLoad.Status.CORRUPT,"Missing beacons section");List<ClassicBeaconRecord> out=new ArrayList<ClassicBeaconRecord>();Set<UUID> ids=new HashSet<UUID>();for(String key:root.getKeys(false)){ConfigurationSection s=root.getConfigurationSection(key);ClassicBeaconRecord r=parse(key,s);if(!ids.add(r.getUniqueId()))throw new IllegalArgumentException("Duplicate id");out.add(r);}return ClassicStorageLoad.success(out);}catch(IOException e){return ClassicStorageLoad.failure(ClassicStorageLoad.Status.UNAVAILABLE,"Cannot read storage");}catch(InvalidConfigurationException e){return ClassicStorageLoad.failure(ClassicStorageLoad.Status.CORRUPT,"Invalid YAML");}catch(RuntimeException e){return ClassicStorageLoad.failure(ClassicStorageLoad.Status.CORRUPT,e.getMessage());}}
    public void store(Collection<ClassicBeaconRecord> records){YamlConfiguration y=new YamlConfiguration();y.createSection("beacons");for(ClassicBeaconRecord r:records){String p="beacons."+r.getLocation().key()+".";y.set(p+"unique-id",r.getUniqueId().toString());y.set(p+"owner",r.getOwner()==null?null:r.getOwner().toString());y.set(p+"range",r.getRange());y.set(p+"level",r.getLevel());y.set(p+"effects",r.getEffects());y.set(p+"active-effects",new ArrayList<String>(r.getActiveEffects()));List<String> trusted=new ArrayList<String>();for(UUID id:r.getTrusted())trusted.add(id.toString());y.set(p+"trusted",trusted);y.set(p+"protect-base-blocks",r.isProtectBase());y.set(p+"beam-style",r.getBeamStyle());y.set(p+"range-particles-enabled",r.isRangeParticles());y.set(p+"range-particle-type",r.getRangeParticleType());}
        Path temp=null;try{File parent=file.getAbsoluteFile().getParentFile();Files.createDirectories(parent.toPath());temp=Files.createTempFile(parent.toPath(),file.getName()+".",".tmp");Files.write(temp,y.saveToString().getBytes(StandardCharsets.UTF_8));ClassicYamlBeaconStorage verify=new ClassicYamlBeaconStorage(temp.toFile());ClassicStorageLoad loaded=verify.load();if(!loaded.isSuccessful()||loaded.getRecords().size()!=records.size()||!new HashSet<ClassicBeaconRecord>(loaded.getRecords()).equals(new HashSet<ClassicBeaconRecord>(records)))throw new ClassicStorageException("Storage verification failed");try{Files.move(temp,file.toPath(),StandardCopyOption.REPLACE_EXISTING,StandardCopyOption.ATOMIC_MOVE);}catch(java.nio.file.AtomicMoveNotSupportedException e){Files.move(temp,file.toPath(),StandardCopyOption.REPLACE_EXISTING);}temp=null;}catch(IOException e){throw new ClassicStorageException("Cannot persist storage",e);}finally{if(temp!=null)try{Files.deleteIfExists(temp);}catch(IOException ignored){}}}
    public void close(){}
    private static ClassicBeaconRecord parse(String key,ConfigurationSection s){if(s==null)throw new IllegalArgumentException("Beacon entry is not a section");UUID id=UUID.fromString(req(s.getString("unique-id"),"unique-id"));String ownerRaw=s.getString("owner");UUID owner=ownerRaw==null?null:UUID.fromString(ownerRaw);Map<String,Integer> effects=new TreeMap<String,Integer>();ConfigurationSection es=s.getConfigurationSection("effects");if(es==null)throw new IllegalArgumentException("effects is not a section");for(String e:es.getKeys(false))effects.put(e,Integer.valueOf(es.getInt(e)));Set<String> active=new HashSet<String>(s.getStringList("active-effects"));Set<UUID> trusted=new HashSet<UUID>();for(String v:s.getStringList("trusted"))trusted.add(UUID.fromString(v));return new ClassicBeaconRecord(ClassicBeaconLocation.parse(key),id,owner,s.getInt("range"),s.getInt("level"),effects,active,trusted,s.getBoolean("protect-base-blocks"),s.getString("beam-style"),s.getBoolean("range-particles-enabled"),req(s.getString("range-particle-type"),"range particle"));}
    private static String req(String s,String n){if(s==null||s.trim().isEmpty())throw new IllegalArgumentException("Missing "+n);return s;}
}
