package cl.dynasty.nexusbeacon.platform.classic;

import java.util.ArrayList;import java.util.List;import java.util.Map;import java.util.UUID;
import org.bukkit.Bukkit;import org.bukkit.ChatColor;import org.bukkit.GameMode;import org.bukkit.Material;import org.bukkit.block.Block;import org.bukkit.entity.Player;import org.bukkit.event.EventHandler;import org.bukkit.event.EventPriority;import org.bukkit.event.Listener;import org.bukkit.event.block.Action;import org.bukkit.event.block.BlockBreakEvent;import org.bukkit.event.block.BlockPlaceEvent;import org.bukkit.event.inventory.InventoryClickEvent;import org.bukkit.event.inventory.InventoryDragEvent;import org.bukkit.event.player.PlayerInteractEvent;import org.bukkit.inventory.Inventory;import org.bukkit.inventory.ItemStack;import org.bukkit.inventory.meta.ItemMeta;

public final class ClassicCoreListener implements Listener {
 private static final int[] CONTENT={10,11,12,13,14,15,16,19,20,21,22,23,24,25,28,29,30,31,32,33,34};
 private final ClassicApplicationState state;private final ClassicBeaconTransactions tx;private final ClassicBeaconItemFactory items;private final boolean ownerOnly;private final boolean autoPickup;private final boolean creativeNoDupe;private final ClassicEffectCatalog effects;private final List<String> beamIds;private final ClassicGuiMutationService mutations;
 public ClassicCoreListener(ClassicApplicationState s,ClassicBeaconTransactions t,ClassicBeaconItemFactory i,boolean o,boolean a,boolean c,ClassicEffectCatalog effects,ClassicBeamStyleCatalog beams){state=s;tx=t;items=i;ownerOnly=o;autoPickup=a;creativeNoDupe=c;this.effects=effects;beamIds=new ArrayList<String>(beams.getStyles().keySet());mutations=new ClassicGuiMutationService(s,beams.getStyles());}
 @EventHandler(priority=EventPriority.HIGHEST,ignoreCancelled=true) public void place(BlockPlaceEvent e){if(e.getBlockPlaced().getType()!=Material.BEACON)return;ClassicBeaconTransactions.Result r=tx.place(e.getItemInHand(),loc(e.getBlockPlaced()),e.getPlayer().getUniqueId(),!e.canBuild());if(r.getStatus()==ClassicBeaconTransactions.Status.UNMARKED)return;if(!r.isCommitted()){e.setCancelled(true);e.getPlayer().sendMessage(ChatColor.RED+"NexusBeacon placement failed safely.");}}
 @EventHandler(priority=EventPriority.HIGHEST,ignoreCancelled=true) public void remove(BlockBreakEvent e){ClassicBeaconRecord current=state.find(loc(e.getBlock()));if(current==null)return;Player p=e.getPlayer();UUID id=p.getUniqueId();if(ownerOnly&&!p.hasPermission("NexusBeacon.admin")&&!id.equals(current.getOwner())&&!current.getTrusted().contains(id)){e.setCancelled(true);p.sendMessage(ChatColor.RED+"You cannot break this NexusBeacon.");return;}ItemStack returned=returnsPortable(p.getGameMode(),creativeNoDupe)?items.createPortable(current):null;ClassicBeaconTransactions.Result r=tx.remove(current.getLocation(),e.isCancelled());if(!r.isCommitted()){e.setCancelled(true);p.sendMessage(ChatColor.RED+"NexusBeacon removal failed safely.");return;}e.setDropItems(false);if(returned!=null){if(autoPickup){Map<Integer,ItemStack> left=p.getInventory().addItem(returned);for(ItemStack x:left.values())e.getBlock().getWorld().dropItemNaturally(e.getBlock().getLocation(),x);}else e.getBlock().getWorld().dropItemNaturally(e.getBlock().getLocation(),returned);}}
 @EventHandler(priority=EventPriority.HIGHEST,ignoreCancelled=true) public void interact(PlayerInteractEvent e){if(!opensGui(e.getAction()))return;Block b=e.getClickedBlock();if(b==null||b.getType()!=Material.BEACON)return;ClassicBeaconRecord r=state.find(loc(b));if(r==null)return;UUID id=e.getPlayer().getUniqueId();if(ownerOnly&&!e.getPlayer().hasPermission("NexusBeacon.admin")&&!id.equals(r.getOwner())&&!r.getTrusted().contains(id)){e.setCancelled(true);return;}e.setCancelled(true);open(e.getPlayer(),r,ClassicGuiHolder.Menu.MAIN);}
 private void open(Player p,ClassicBeaconRecord r,ClassicGuiHolder.Menu menu){if(r==null){p.closeInventory();return;}ClassicGuiHolder h=new ClassicGuiHolder(r.getLocation(),menu);Inventory inv=Bukkit.createInventory(h,54,title(menu));h.setInventory(inv);if(menu==ClassicGuiHolder.Menu.MAIN)main(inv,r);else if(menu==ClassicGuiHolder.Menu.EFFECTS)effectMenu(inv,r);else beamMenu(inv,r);p.openInventory(inv);}
 private void main(Inventory inv,ClassicBeaconRecord r){inv.setItem(20,item(Material.NETHER_STAR,ChatColor.AQUA+"Effects",ChatColor.GRAY+"Browse supported effects",ChatColor.GRAY+"Owned: "+r.getEffects().size(),ChatColor.YELLOW+"Executors unavailable in Classic core"));inv.setItem(22,item(Material.ENDER_EYE,ChatColor.AQUA+"Range visualization",r.isRangeParticles()?ChatColor.GREEN+"Enabled":ChatColor.RED+"Disabled",ChatColor.GRAY+"Range: "+r.getRange(),ChatColor.GRAY+"Click to toggle"));inv.setItem(24,item(Material.BEACON,ChatColor.AQUA+"Beam styles",ChatColor.GRAY+"Current: "+(r.getBeamStyle()==null?"global":r.getBeamStyle()),ChatColor.GRAY+"Click to select"));inv.setItem(49,item(Material.BARRIER,ChatColor.RED+"Close"));}
 private void effectMenu(Inventory inv,ClassicBeaconRecord r){List<ClassicEffectCatalog.Definition> defs=effects.getDefinitions();for(int i=0;i<defs.size()&&i<CONTENT.length;i++){ClassicEffectCatalog.Definition d=defs.get(i);boolean owned=r.getEffects().containsKey(d.getId());boolean active=r.getActiveEffects().contains(d.getId());String status=active?ChatColor.GREEN+"Active (saved state)":owned?ChatColor.GRAY+"Owned, inactive":ChatColor.YELLOW+"Not owned";inv.setItem(CONTENT[i],item(d.getIcon(),ChatColor.AQUA+d.getId(),status,ChatColor.RED+"Executor unavailable",ChatColor.GRAY+"Purchase and activation disabled"));}inv.setItem(49,item(Material.ARROW,ChatColor.YELLOW+"Back"));}
 private void beamMenu(Inventory inv,ClassicBeaconRecord r){for(int i=0;i<beamIds.size()&&i<CONTENT.length;i++){String id=beamIds.get(i);boolean selected=id.equalsIgnoreCase(r.getBeamStyle());inv.setItem(CONTENT[i],item(Material.BEACON,ChatColor.AQUA+id,selected?ChatColor.GREEN+"Selected":ChatColor.GRAY+"Click to select"));}inv.setItem(49,item(Material.ARROW,ChatColor.YELLOW+"Back"));}
 @EventHandler public void click(InventoryClickEvent e){Inventory top=e.getView().getTopInventory();if(!(top.getHolder() instanceof ClassicGuiHolder))return;e.setCancelled(true);if(!(e.getWhoClicked() instanceof Player)||e.getRawSlot()<0||e.getRawSlot()>=top.getSize())return;Player p=(Player)e.getWhoClicked();ClassicGuiHolder h=(ClassicGuiHolder)top.getHolder();ClassicBeaconRecord r=state.find(h.getLocation());if(r==null){p.closeInventory();return;}int slot=e.getRawSlot();if(h.getMenu()==ClassicGuiHolder.Menu.MAIN){if(slot==20)open(p,r,ClassicGuiHolder.Menu.EFFECTS);else if(slot==22){mutations.toggleRange(h.getLocation());open(p,state.find(h.getLocation()),ClassicGuiHolder.Menu.MAIN);}else if(slot==24)open(p,r,ClassicGuiHolder.Menu.BEAM_STYLES);else if(slot==49)p.closeInventory();return;}if(slot==49){open(p,r,ClassicGuiHolder.Menu.MAIN);return;}if(h.getMenu()==ClassicGuiHolder.Menu.BEAM_STYLES){int index=index(slot);if(index>=0&&index<beamIds.size()&&mutations.selectBeam(h.getLocation(),beamIds.get(index))==ClassicGuiMutationService.Result.COMMITTED)open(p,state.find(h.getLocation()),ClassicGuiHolder.Menu.BEAM_STYLES);return;}if(h.getMenu()==ClassicGuiHolder.Menu.EFFECTS&&index(slot)>=0)p.sendMessage(ChatColor.YELLOW+"This effect is visible for compatibility, but its executor and purchase path are not available yet.");}
 @EventHandler public void drag(InventoryDragEvent e){if(e.getView().getTopInventory().getHolder() instanceof ClassicGuiHolder)e.setCancelled(true);}
 private static int index(int slot){for(int i=0;i<CONTENT.length;i++)if(CONTENT[i]==slot)return i;return -1;}
 static boolean opensGui(Action action){return action==Action.RIGHT_CLICK_BLOCK;}
 static boolean returnsPortable(GameMode mode,boolean configuredCreativeNoDupe){return true;}
 private static ItemStack item(Material material,String name,String...lore){ItemStack i=new ItemStack(material);ItemMeta meta=i.getItemMeta();meta.setDisplayName(name);List<String> lines=new ArrayList<String>();for(String line:lore)lines.add(line);meta.setLore(lines);i.setItemMeta(meta);return i;}
 private static String title(ClassicGuiHolder.Menu menu){if(menu==ClassicGuiHolder.Menu.EFFECTS)return ChatColor.DARK_GRAY+"NexusBeacon Effects";if(menu==ClassicGuiHolder.Menu.BEAM_STYLES)return ChatColor.DARK_GRAY+"NexusBeacon Beam";return ChatColor.DARK_GRAY+"NexusBeacon";}
 private static ClassicBeaconLocation loc(Block b){return new ClassicBeaconLocation(b.getWorld().getName(),b.getX(),b.getY(),b.getZ());}
}
