package cl.dynasty.nexusbeacon.platform.classic;
import java.util.Collection;import java.util.function.BooleanSupplier;import org.bukkit.Color;import org.bukkit.Location;import org.bukkit.Material;import org.bukkit.Particle;import org.bukkit.World;import org.bukkit.configuration.ConfigurationSection;import org.bukkit.plugin.Plugin;import cl.dynasty.nexusbeacon.platform.api.ScheduledTaskHandle;import cl.dynasty.nexusbeacon.platform.api.SchedulerService;import cl.dynasty.nexusbeacon.platform.api.VerticalBeamGeometry;
public final class ClassicBeamRuntime implements Runnable {
 interface Records{Collection<ClassicBeaconRecord> snapshot();boolean authoritative(ClassicBeaconRecord r);}interface WorldView{boolean available(ClassicBeaconRecord r);boolean chunkLoaded(ClassicBeaconRecord r);boolean beaconPresent(ClassicBeaconRecord r);Material materialAt(ClassicBeaconRecord r,int x,int y,int z);}interface Emitter{void emit(ClassicBeaconRecord r,ClassicBeamStyle s,int height,double step,int count,BooleanSupplier authority);}
 private final Records records;private final WorldView worlds;private final Emitter emitter;private final SchedulerService scheduler;private final ClassicBeamRenderPolicy policy;private final ClassicBeamStyleCatalog styles;private final String styleMode;private final int height;private final double step;private final int count;private final long interval;private ScheduledTaskHandle task;private boolean running;
 public static ClassicBeamRuntime create(final Plugin plugin,final ClassicApplicationState state,ConfigurationSection config,ClassicParticleResolver particles,SchedulerService scheduler){final ClassicBeamRenderPolicy policy=new ClassicBeamRenderPolicy(config,new ClassicMaterialResolver());final ClassicBeamStyleCatalog styles=new ClassicBeamStyleCatalog(config,particles);Records records=new Records(){public Collection<ClassicBeaconRecord> snapshot(){return state.snapshot();}public boolean authoritative(ClassicBeaconRecord r){return state.isAuthoritative(r);}};WorldView worlds=new WorldView(){private World world(ClassicBeaconRecord r){return plugin.getServer().getWorld(r.getLocation().getWorld());}public boolean available(ClassicBeaconRecord r){return world(r)!=null;}public boolean chunkLoaded(ClassicBeaconRecord r){World w=world(r);return w!=null&&w.isChunkLoaded(r.getLocation().getX()>>4,r.getLocation().getZ()>>4);}public boolean beaconPresent(ClassicBeaconRecord r){World w=world(r);return w!=null&&w.getBlockAt(r.getLocation().getX(),r.getLocation().getY(),r.getLocation().getZ()).getType()==Material.BEACON;}public Material materialAt(ClassicBeaconRecord r,int x,int y,int z){World w=world(r);return w==null?null:w.getBlockAt(x,y,z).getType();}};Emitter emitter=new Emitter(){public void emit(final ClassicBeaconRecord r,final ClassicBeamStyle style,int h,double st,int c,final BooleanSupplier authority){World world=plugin.getServer().getWorld(r.getLocation().getWorld());if(world==null)return;final Location base=new Location(world,r.getLocation().getX()+.5D,r.getLocation().getY()+1D,r.getLocation().getZ()+.5D);final int amount=c;VerticalBeamGeometry.forEachPoint(base,h,st,point->{if(!authority.getAsBoolean())return;Particle particle=style.getParticle();Color color=style.getColor();String particleName=particle.name();if(color!=null&&("REDSTONE".equals(particleName)||"DUST".equals(particleName)))world.spawnParticle(particle,point,amount,0,0,0,0,new Particle.DustOptions(color,style.getSize()));else world.spawnParticle(particle,point,amount,0,0,0,0);});}};return new ClassicBeamRuntime(records,worlds,emitter,scheduler,policy,styles,config.getString("visual-beam.style-mode","PLAYER_OR_GLOBAL"),config.getInt("visual-beam.height",96),config.getDouble("visual-beam.step",.45D),config.getInt("visual-beam.count",1),config.getLong("visual-beam.interval-ticks",4L));}
 ClassicBeamRuntime(Records records,WorldView worlds,Emitter emitter,SchedulerService scheduler,ClassicBeamRenderPolicy policy,ClassicBeamStyleCatalog styles,String mode,int height,double step,int count,long interval){this.records=records;this.worlds=worlds;this.emitter=emitter;this.scheduler=scheduler;this.policy=policy;this.styles=styles;styleMode=mode;this.height=Math.max(1,height);this.step=Math.max(.25D,step);this.count=Math.max(1,count);this.interval=Math.max(1L,interval);}
 public synchronized void start(){if(running)return;running=true;task=scheduler.runSyncTimer(this,interval,interval);}public void run(){if(!running)return;for(final ClassicBeaconRecord r:records.snapshot()){if(!eligible(r))continue;ClassicBeamStyle style=styles.resolve(r.getBeamStyle(),styleMode);if(style==null)continue;emitter.emit(r,style,height,step,count,new BooleanSupplier(){public boolean getAsBoolean(){return running&&eligible(r);}});}}
 private boolean eligible(final ClassicBeaconRecord r){return records.authoritative(r)&&worlds.available(r)&&worlds.chunkLoaded(r)&&worlds.beaconPresent(r)&&policy.shouldRender(r,new ClassicBeamRenderPolicy.MaterialLookup(){public Material at(int x,int y,int z){return worlds.materialAt(r,x,y,z);}});}
 public synchronized void close(){running=false;if(task!=null)task.cancel();task=null;}public synchronized boolean isRunning(){return running;}public synchronized int getTaskCount(){return task==null?0:1;}public int getStyleCount(){return styles.size();}
}
