package cl.dynasty.nexusbeacon.platform.classic;
import org.bukkit.Bukkit;import org.bukkit.Material;import org.bukkit.World;import org.bukkit.block.Block;import org.bukkit.block.Furnace;import org.bukkit.event.EventHandler;import org.bukkit.event.Listener;import org.bukkit.event.inventory.FurnaceBurnEvent;import org.bukkit.event.inventory.FurnaceSmeltEvent;import org.bukkit.plugin.Plugin;
/** Event-driven stable-product FurnaceBoost semantics for Classic Bukkit. */
final class ClassicFurnaceBoostListener implements Listener {
 static final class Boost {final double cookPercent,fuelPercent;Boost(double cook,double fuel){cookPercent=cook;fuelPercent=fuel;}}
 private final Plugin plugin;private final ClassicApplicationState state;private final ClassicEffectCatalog catalog;
 ClassicFurnaceBoostListener(Plugin plugin,ClassicApplicationState state,ClassicEffectCatalog catalog){this.plugin=plugin;this.state=state;this.catalog=catalog;}
 @EventHandler(ignoreCancelled=true)public void burn(FurnaceBurnEvent event){Boost boost=findBest(event.getBlock());if(boost!=null)event.setBurnTime(reducedBurnTime(event.getBurnTime(),boost.fuelPercent));}
 @EventHandler(ignoreCancelled=true)public void smelt(FurnaceSmeltEvent event){if(findBest(event.getBlock())==null)return;final Block block=event.getBlock();Bukkit.getScheduler().runTask(plugin,new Runnable(){public void run(){Boost boost=findBest(block);if(boost==null||!(block.getState() instanceof Furnace))return;Furnace furnace=(Furnace)block.getState();if(furnace.getInventory().getSmelting()==null)return;int total=block.getType()==Material.FURNACE?200:100;furnace.setCookTime((short)advancedCookTime(furnace.getCookTime(),total,boost.cookPercent));furnace.update(true);}});}
 Boost findBest(Block block){Boost best=null;if(block==null)return null;for(ClassicBeaconRecord record:state.snapshot()){boolean authority=authoritative(record,block.getWorld());boolean inside=insideHorizontal(block.getX(),block.getZ(),record.getLocation().getX(),record.getLocation().getZ(),record.getRange());if(!eligible(authority,true,inside))continue;for(String id:record.getActiveEffects()){ClassicEffectCatalog.Definition definition=catalog.get(id);Integer acquired=record.getEffects().get(id);if(definition==null||acquired==null||!"BLOCK_PROCESS_BOOST".equals(definition.getType())||!definition.getTargetBlocks().contains(block.getType()))continue;int level=Math.min(definition.getMaxLevel(),Math.max(1,acquired.intValue()));Boost candidate=new Boost(definition.levelDouble(level,"speed-up-time",8D),definition.levelDouble(level,"fuel-speed-up-time",8D));best=best(best,candidate);}}return best;}
 private boolean authoritative(ClassicBeaconRecord record,World furnaceWorld){ClassicBeaconLocation location=record.getLocation();World world=Bukkit.getWorld(location.getWorld());return world!=null&&world.equals(furnaceWorld)&&state.isAuthoritative(record)&&world.isChunkLoaded(location.getX()>>4,location.getZ()>>4)&&world.getBlockAt(location.getX(),location.getY(),location.getZ()).getType()==Material.BEACON;}
 static int reducedBurnTime(int burnTime,double percent){int reduction=(int)(burnTime*(percent/100D));return Math.max(1,burnTime-reduction);}static int advancedCookTime(int current,int total,double percent){int add=(int)(total*(percent/100D));return Math.min(total,current+add);}static boolean insideHorizontal(int x,int z,int beaconX,int beaconZ,int range){double dx=x-beaconX,dz=z-beaconZ;return dx*dx+dz*dz<=range*range;}static boolean eligible(boolean authoritative,boolean active,boolean inside){return authoritative&&active&&inside;}static Boost best(Boost... boosts){Boost best=null;for(Boost boost:boosts)if(boost!=null&&(best==null||boost.cookPercent>best.cookPercent))best=boost;return best;}
}
