package cl.dynasty.nexusbeacon.platform.classic;
import java.util.ArrayList;import java.util.Collections;import java.util.LinkedHashMap;import java.util.List;import java.util.Locale;import java.util.Map;import org.bukkit.Material;import org.bukkit.configuration.ConfigurationSection;import org.bukkit.potion.PotionEffectType;import cl.dynasty.nexusbeacon.platform.api.MaterialContext;import cl.dynasty.nexusbeacon.platform.api.MaterialResolution;import cl.dynasty.nexusbeacon.platform.api.PotionEffectResolution;
public final class ClassicEffectCatalog {
 public static final class Definition {private final String id,type,target;private final Material icon;private final PotionEffectType potion;private final int maxLevel,duration,amplifier;private final List<Material> targetBlocks;private final ConfigurationSection config;Definition(String id,String type,String target,Material icon,PotionEffectType potion,int maxLevel,int duration,int amplifier,List<Material> blocks,ConfigurationSection config){this.id=id;this.type=type;this.target=target;this.icon=icon;this.potion=potion;this.maxLevel=maxLevel;this.duration=duration;this.amplifier=amplifier;targetBlocks=Collections.unmodifiableList(blocks);this.config=config;}public String getId(){return id;}public String getType(){return type;}public String getTarget(){return target;}public Material getIcon(){return icon;}public PotionEffectType getPotion(){return potion;}public int getMaxLevel(){return maxLevel;}public int getDuration(){return duration;}public int getAmplifier(){return amplifier;}public List<Material> getTargetBlocks(){return targetBlocks;}public int levelInt(int level,String key,int fallback){return config.getInt("levels."+level+"."+key,config.getInt(key+"-per-level",fallback)*level);}public double levelDouble(int level,String key,double fallback){return config.getDouble("levels."+level+"."+key,config.getDouble(key+"-per-level",fallback)*level);}}
 private final Map<String,Definition> definitions;private final List<String> supported;private final List<String> deferred;
 public ClassicEffectCatalog(ConfigurationSection effects,ClassicMaterialResolver materials,ClassicPotionEffectResolver potions){Map<String,Definition> found=new LinkedHashMap<String,Definition>();List<String>d=new ArrayList<String>();if(effects!=null)for(String raw:effects.getKeys(false)){ConfigurationSection e=effects.getConfigurationSection(raw);if(e==null||!e.getBoolean("enabled",true))continue;String id=raw.toLowerCase(Locale.ROOT),type=e.getString("type","").toUpperCase(Locale.ROOT);d.add(id);MaterialResolution iconResolution=materials.resolveMaterial(e.getString("icon"),MaterialContext.EFFECT_ICON);Material icon=iconResolution.isResolved()?iconResolution.getMaterial().get():Material.NETHER_STAR;PotionEffectType potion=null;boolean supported=known(type);if("POTION".equals(type)){PotionEffectResolution resolution=potions.resolvePotionEffect(e.getString("potion"));supported=resolution.isResolved();potion=resolution.getEffectType().orElse(null);}List<Material> blocks=new ArrayList<Material>();if("BLOCK_PROCESS_BOOST".equals(type)){List<String> names=e.getStringList("target-blocks");if(names.isEmpty())names=Collections.singletonList("FURNACE");for(String name:names){MaterialResolution block=materials.resolveMaterial(name,MaterialContext.BLOCK_MATCH);if(!block.isResolved())supported=false;else blocks.add(block.getMaterial().get());}}if(supported)found.put(id,new Definition(id,type,e.getString("target","PLAYERS").toUpperCase(Locale.ROOT),icon,potion,Math.max(1,e.getInt("max-level",1)),Math.max(1,e.getInt("duration-ticks",100)),Math.max(1,e.getInt("amplifier-per-level",1)),blocks,e));}definitions=Collections.unmodifiableMap(found);supported=Collections.unmodifiableList(new ArrayList<String>(found.keySet()));deferred=Collections.unmodifiableList(d);}
 public Definition get(String id){return id==null?null:definitions.get(id.toLowerCase(Locale.ROOT));}public List<Definition> getDefinitions(){return Collections.unmodifiableList(new ArrayList<Definition>(definitions.values()));}public List<String> getSupportedDefinitions(){return supported;}public List<String> getDeferredExecutors(){return deferred;}
 private static boolean known(String type){return "POTION".equals(type)||"CROP_BOOST".equals(type)||"SPAWNER_BOOST".equals(type)||"IGNITION".equals(type)||"DAMAGE_FIELD".equals(type)||"GRAVITY_PULSE".equals(type)||"BLOCK_PROCESS_BOOST".equals(type);}
}
