package cl.dynasty.nexusbeacon.platform.classic;
import java.util.ArrayList;import java.util.Arrays;import java.util.Collections;import java.util.HashSet;import java.util.List;import java.util.Locale;import java.util.Set;import java.util.UUID;import org.bukkit.Bukkit;import org.bukkit.ChatColor;import org.bukkit.Material;import org.bukkit.OfflinePlayer;import org.bukkit.block.Block;import org.bukkit.command.Command;import org.bukkit.command.CommandSender;import org.bukkit.command.TabExecutor;import org.bukkit.entity.Player;
public final class ClassicNexusBeaconCommand implements TabExecutor {private static final List<String> ROOT=Collections.unmodifiableList(Arrays.asList("help","give","trust","trusted","untrust"));private final ClassicApplicationState state;private final ClassicBeaconItemFactory items;
 public ClassicNexusBeaconCommand(ClassicApplicationState s,ClassicBeaconItemFactory i){state=s;items=i;}
 public boolean onCommand(CommandSender sender,Command command,String label,String[] args){if(args.length==0||"help".equalsIgnoreCase(args[0])){help(sender);return true;}if("give".equalsIgnoreCase(args[0])){if(!sender.hasPermission("NexusBeacon.admin")){sender.sendMessage(ChatColor.RED+"No permission.");return true;}Player target=args.length>1?Bukkit.getPlayerExact(args[1]):sender instanceof Player?(Player)sender:null;if(target==null){sender.sendMessage(ChatColor.RED+"Player not found.");return true;}int amount=1;if(args.length>2)try{amount=Math.max(1,Math.min(64,Integer.parseInt(args[2])));}catch(NumberFormatException invalid){sender.sendMessage(ChatColor.RED+"Amount must be a number from 1 to 64.");return true;}target.getInventory().addItem(items.createNew(amount));return true;}if(!isCore(args[0])){help(sender);return true;}if(!(sender instanceof Player)){sender.sendMessage(ChatColor.RED+"This command requires a player.");return true;}Player p=(Player)sender;ClassicBeaconRecord r=target(p);if(r==null){p.sendMessage(ChatColor.RED+"Look at a managed NexusBeacon.");return true;}if(!p.hasPermission("NexusBeacon.admin")&&!p.getUniqueId().equals(r.getOwner())){p.sendMessage(ChatColor.RED+"Only the owner may change trust.");return true;}if("trusted".equalsIgnoreCase(args[0])){p.sendMessage(ChatColor.AQUA+"Trusted: "+r.getTrusted());return true;}if(args.length<2){p.sendMessage(ChatColor.RED+"Usage: /nb "+args[0]+" <player>");return true;}OfflinePlayer other=Bukkit.getOfflinePlayer(args[1]);UUID id=other.getUniqueId();Set<UUID> next=new HashSet<UUID>(r.getTrusted());if("trust".equalsIgnoreCase(args[0]))next.add(id);else next.remove(id);try{state.update(r.withTrusted(next));p.sendMessage(ChatColor.GREEN+"Trust updated.");}catch(ClassicStorageException failure){p.sendMessage(ChatColor.RED+"Trust update failed safely.");}return true;}
 public List<String> onTabComplete(CommandSender sender,Command command,String alias,String[] args){if(args.length==1)return matches(ROOT,args[0]);if(args.length==2&&("give".equalsIgnoreCase(args[0])||"trust".equalsIgnoreCase(args[0])||"untrust".equalsIgnoreCase(args[0]))){List<String> names=new ArrayList<String>();for(Player player:Bukkit.getOnlinePlayers())names.add(player.getName());return matches(names,args[1]);}if(args.length==3&&"give".equalsIgnoreCase(args[0]))return matches(Arrays.asList("1","16","32","64"),args[2]);return Collections.emptyList();}
 static List<String> matches(List<String> values,String prefix){String normalized=prefix==null?"":prefix.toLowerCase(Locale.ROOT);List<String> result=new ArrayList<String>();for(String value:values)if(value.toLowerCase(Locale.ROOT).startsWith(normalized))result.add(value);return result;}
 private static boolean isCore(String value){return "trust".equalsIgnoreCase(value)||"trusted".equalsIgnoreCase(value)||"untrust".equalsIgnoreCase(value);}
 private static void help(CommandSender sender){sender.sendMessage(ChatColor.AQUA+"NexusBeacon Classic commands:");sender.sendMessage(ChatColor.GRAY+"/nb help");sender.sendMessage(ChatColor.GRAY+"/nb give [player] [amount]");sender.sendMessage(ChatColor.GRAY+"/nb trust <player>");sender.sendMessage(ChatColor.GRAY+"/nb trusted");sender.sendMessage(ChatColor.GRAY+"/nb untrust <player>");}
 private ClassicBeaconRecord target(Player p){Block b=p.getTargetBlock((Set<Material>)null,6);if(b==null||b.getType()!=Material.BEACON)return null;return state.find(new ClassicBeaconLocation(b.getWorld().getName(),b.getX(),b.getY(),b.getZ()));}}
