package cl.dynasty.nexusbeacon.platform.classic;
import java.util.ArrayList;import java.util.Collection;import java.util.HashMap;import java.util.List;import java.util.Map;import java.util.UUID;import org.bukkit.Bukkit;import org.bukkit.Location;import org.bukkit.Particle;import org.bukkit.World;import org.bukkit.plugin.Plugin;import org.bukkit.scheduler.BukkitTask;
public final class ClassicVisualRuntime {
 interface Records{Collection<ClassicBeaconRecord> snapshot();}
 interface WorldView{boolean beaconPresent(ClassicBeaconRecord r);boolean chunkLoaded(ClassicBeaconRecord r,int x,int z);int highestY(ClassicBeaconRecord r,int x,int z);int minY(ClassicBeaconRecord r);int maxY(ClassicBeaconRecord r);}
 interface Emitter{void emit(ClassicBeaconRecord r,Particle particle,double x,double y,double z);}
 static final class Point{final double x,y,z;Point(double x,double y,double z){this.x=x;this.y=y;this.z=z;}}
 private static final int TERRAIN_OFFSET=20;private static final int MIN_RADIUS_POINTS=8;private static final int CACHE_REFRESH_TICKS=20;
 private final Plugin plugin;private final Records records;private final ClassicParticleResolver particles;private final WorldView worlds;private final Emitter emitter;private final int radiusPoints;private final Map<UUID,Cache> cache=new HashMap<UUID,Cache>();private BukkitTask task;private int tick;
 public ClassicVisualRuntime(final Plugin plugin,final ClassicApplicationState state,ClassicParticleResolver particles,int radiusPoints){this.plugin=plugin;this.records=new Records(){public Collection<ClassicBeaconRecord> snapshot(){return state.snapshot();}};this.particles=particles;this.radiusPoints=safeRadiusPoints(radiusPoints);this.worlds=new WorldView(){private World world(ClassicBeaconRecord r){return Bukkit.getWorld(r.getLocation().getWorld());}public boolean beaconPresent(ClassicBeaconRecord r){World w=world(r);return w!=null&&w.getBlockAt(r.getLocation().getX(),r.getLocation().getY(),r.getLocation().getZ()).getType()==org.bukkit.Material.BEACON;}public boolean chunkLoaded(ClassicBeaconRecord r,int x,int z){World w=world(r);return w!=null&&w.isChunkLoaded(x>>4,z>>4);}public int highestY(ClassicBeaconRecord r,int x,int z){return world(r).getHighestBlockYAt(x,z);}public int minY(ClassicBeaconRecord r){return ClassicWorldHeightCompatibility.minimumHeight(world(r));}public int maxY(ClassicBeaconRecord r){return world(r).getMaxHeight()-1;}};this.emitter=new Emitter(){public void emit(ClassicBeaconRecord r,Particle particle,double x,double y,double z){World w=Bukkit.getWorld(r.getLocation().getWorld());if(w!=null)w.spawnParticle(particle,new Location(w,x,y,z),1);}};}
 ClassicVisualRuntime(Records records,ClassicParticleResolver particles,WorldView worlds,Emitter emitter,int radiusPoints){this.plugin=null;this.records=records;this.particles=particles;this.worlds=worlds;this.emitter=emitter;this.radiusPoints=safeRadiusPoints(radiusPoints);}
 public void start(long interval){if(task!=null)return;task=Bukkit.getScheduler().runTaskTimer(plugin,new Runnable(){public void run(){tick();}},interval,interval);}public void stop(){if(task!=null){task.cancel();task=null;}cache.clear();}
 void tick(){tick++;for(ClassicBeaconRecord r:records.snapshot()){if(!r.isRangeParticles()||!worlds.beaconPresent(r))continue;ClassicParticleResolution resolution=particles.resolve(r.getRangeParticleType());if(!resolution.isResolved())continue;Cache current=cache.get(r.getUniqueId());if(current==null||current.range!=r.getRange()||tick-current.builtAt>=CACHE_REFRESH_TICKS){current=new Cache(r.getRange(),tick,perimeter(r));cache.put(r.getUniqueId(),current);}for(Point point:current.points)emitter.emit(r,resolution.getParticle().get(),point.x,point.y,point.z);}}
 List<Point> perimeter(ClassicBeaconRecord r){List<Point> points=new ArrayList<Point>(radiusPoints);for(int i=0;i<radiusPoints;i++){double angle=Math.PI*2D*i/radiusPoints;double x=r.getLocation().getX()+.5D+Math.cos(angle)*r.getRange();double z=r.getLocation().getZ()+.5D+Math.sin(angle)*r.getRange();int blockX=(int)Math.floor(x),blockZ=(int)Math.floor(z);if(!worlds.chunkLoaded(r,blockX,blockZ))continue;int desired=Math.max(r.getLocation().getY(),worlds.highestY(r,blockX,blockZ))+TERRAIN_OFFSET;int y=Math.max(worlds.minY(r),Math.min(worlds.maxY(r),desired));points.add(new Point(x,y+.5D,z));}return points;}
 static int safeRadiusPoints(int configured){return Math.max(MIN_RADIUS_POINTS,configured);}
 int cachedPointCount(UUID id){Cache value=cache.get(id);return value==null?0:value.points.size();}public boolean isRunning(){return task!=null;}
 private static final class Cache{final int range,builtAt;final List<Point> points;Cache(int range,int builtAt,List<Point> points){this.range=range;this.builtAt=builtAt;this.points=points;}}
}
