package cl.dynasty.nexusbeacon.platform.classic;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import org.bukkit.Bukkit;
import org.bukkit.ChatColor;
import org.bukkit.GameMode;
import org.bukkit.Material;
import org.bukkit.block.Block;
import org.bukkit.entity.Player;
import org.bukkit.event.EventHandler;
import org.bukkit.event.EventPriority;
import org.bukkit.event.Listener;
import org.bukkit.event.block.Action;
import org.bukkit.event.block.BlockBreakEvent;
import org.bukkit.event.block.BlockPlaceEvent;
import org.bukkit.event.inventory.InventoryClickEvent;
import org.bukkit.event.inventory.InventoryDragEvent;
import org.bukkit.event.player.PlayerInteractEvent;
import org.bukkit.inventory.Inventory;
import org.bukkit.inventory.ItemStack;
import org.bukkit.inventory.meta.ItemMeta;

public final class ClassicCoreListener implements Listener {
    private static final int[] CONTENT={10,11,12,13,14,15,16,19,20,21,22,23,24,25,28,29,30,31,32,33,34};
    private final ClassicApplicationState state; private final ClassicBeaconTransactions tx; private final ClassicBeaconItemFactory items;
    private final boolean ownerOnlyBreak,ownerOnlyInteract,autoPickup,creativeNoDupe;
    private final ClassicEffectCatalog effects; private final List<String> beamIds; private final ClassicGuiMutationService mutations; private final ClassicPurchaseService purchases;
    public ClassicCoreListener(ClassicApplicationState state,ClassicBeaconTransactions tx,ClassicBeaconItemFactory items,boolean ownerOnlyBreak,boolean ownerOnlyInteract,boolean autoPickup,boolean creativeNoDupe,ClassicEffectCatalog effects,ClassicBeamStyleCatalog beams,ClassicPurchaseService purchases){this.state=state;this.tx=tx;this.items=items;this.ownerOnlyBreak=ownerOnlyBreak;this.ownerOnlyInteract=ownerOnlyInteract;this.autoPickup=autoPickup;this.creativeNoDupe=creativeNoDupe;this.effects=effects;this.purchases=purchases;beamIds=new ArrayList<String>(beams.getStyles().keySet());mutations=new ClassicGuiMutationService(state,beams.getStyles());}
    @EventHandler(priority=EventPriority.HIGHEST,ignoreCancelled=true) public void place(BlockPlaceEvent e){if(e.getBlockPlaced().getType()!=Material.BEACON)return;ClassicBeaconTransactions.Result r=tx.place(e.getItemInHand(),loc(e.getBlockPlaced()),e.getPlayer().getUniqueId(),!e.canBuild());if(r.getStatus()==ClassicBeaconTransactions.Status.UNMARKED)return;if(!r.isCommitted()){e.setCancelled(true);e.getPlayer().sendMessage(ChatColor.RED+"NexusBeacon placement failed safely.");}}
    @EventHandler(priority=EventPriority.HIGHEST,ignoreCancelled=true) public void remove(BlockBreakEvent e){ClassicBeaconRecord r=state.find(loc(e.getBlock()));if(r==null)return;Player p=e.getPlayer();if(ownerOnlyBreak&&!authorized(p,r)){e.setCancelled(true);p.sendMessage(ChatColor.RED+"You cannot break this NexusBeacon.");return;}ItemStack returned=returnsPortable(p.getGameMode(),creativeNoDupe)?items.createPortable(r):null;ClassicBeaconTransactions.Result result=tx.remove(r.getLocation(),e.isCancelled());if(!result.isCommitted()){e.setCancelled(true);p.sendMessage(ChatColor.RED+"NexusBeacon removal failed safely.");return;}e.setDropItems(false);if(returned!=null){if(autoPickup){Map<Integer,ItemStack> left=p.getInventory().addItem(returned);for(ItemStack x:left.values())e.getBlock().getWorld().dropItemNaturally(e.getBlock().getLocation(),x);}else e.getBlock().getWorld().dropItemNaturally(e.getBlock().getLocation(),returned);}}
    @EventHandler(priority=EventPriority.HIGHEST,ignoreCancelled=true) public void interact(PlayerInteractEvent e){if(!opensGui(e.getAction()))return;Block b=e.getClickedBlock();if(b==null||b.getType()!=Material.BEACON)return;ClassicBeaconRecord r=state.find(loc(b));if(r==null)return;if(ownerOnlyInteract&&!authorized(e.getPlayer(),r)){e.setCancelled(true);return;}e.setCancelled(true);open(e.getPlayer(),r,ClassicGuiHolder.Menu.MAIN,null);}
    private void open(Player p,ClassicBeaconRecord r,ClassicGuiHolder.Menu menu,String effectId){if(r==null){p.closeInventory();return;}ClassicGuiHolder h=new ClassicGuiHolder(r.getLocation(),menu,effectId);Inventory inv=Bukkit.createInventory(h,menu==ClassicGuiHolder.Menu.PAYMENT?27:54,title(menu));h.setInventory(inv);if(menu==ClassicGuiHolder.Menu.MAIN)main(inv,r);else if(menu==ClassicGuiHolder.Menu.EFFECTS)effectMenu(inv,r);else if(menu==ClassicGuiHolder.Menu.BEAM_STYLES)beamMenu(inv,r);else paymentMenu(inv,r,effectId);p.openInventory(inv);}
    private void main(Inventory inv,ClassicBeaconRecord r){inv.setItem(20,item(Material.NETHER_STAR,ChatColor.AQUA+"Effects",ChatColor.GRAY+"Browse productive effects",ChatColor.GRAY+"Owned: "+r.getEffects().size()));inv.setItem(22,item(Material.ENDER_EYE,ChatColor.AQUA+"Range visualization",r.isRangeParticles()?ChatColor.GREEN+"Enabled":ChatColor.RED+"Disabled",ChatColor.GRAY+"Range: "+r.getRange(),ChatColor.GRAY+"Click to toggle"));inv.setItem(24,item(Material.BEACON,ChatColor.AQUA+"Beam styles",ChatColor.GRAY+"Current: "+(r.getBeamStyle()==null?"global":r.getBeamStyle()),ChatColor.GRAY+"Click to select"));inv.setItem(49,item(Material.BARRIER,ChatColor.RED+"Close"));}
    private void effectMenu(Inventory inv,ClassicBeaconRecord r){List<ClassicEffectCatalog.Definition> defs=effects.getDefinitions();for(int i=0;i<defs.size()&&i<CONTENT.length;i++){ClassicEffectCatalog.Definition d=defs.get(i);Integer level=r.getEffects().get(d.getId());boolean active=r.getActiveEffects().contains(d.getId());String status=level==null?ChatColor.YELLOW+"Not owned":active?ChatColor.GREEN+"Active":ChatColor.GRAY+"Owned, inactive";String action=level==null?ChatColor.YELLOW+"Right click to acquire":level.intValue()<d.getMaxLevel()?ChatColor.AQUA+"Left: toggle | Right: upgrade":ChatColor.AQUA+"Left click to toggle";inv.setItem(CONTENT[i],item(d.getIcon(),ChatColor.AQUA+d.getId(),status,ChatColor.GRAY+"Level: "+(level==null?0:level)+"/"+d.getMaxLevel(),action));}inv.setItem(49,item(Material.ARROW,ChatColor.YELLOW+"Back"));}
    private void beamMenu(Inventory inv,ClassicBeaconRecord r){for(int i=0;i<beamIds.size()&&i<CONTENT.length;i++){String id=beamIds.get(i);boolean selected=id.equalsIgnoreCase(r.getBeamStyle());inv.setItem(CONTENT[i],item(Material.BEACON,ChatColor.AQUA+id,selected?ChatColor.GREEN+"Selected":ChatColor.GRAY+"Click to select"));}inv.setItem(49,item(Material.ARROW,ChatColor.YELLOW+"Back"));}
    private void paymentMenu(Inventory inv,ClassicBeaconRecord r,String effectId){ClassicEffectCatalog.Definition d=effects.get(effectId);if(d==null)return;Integer level=r.getEffects().get(effectId);inv.setItem(4,item(d.getIcon(),ChatColor.AQUA+effectId,ChatColor.GRAY+(level==null?"Acquire level 1":"Upgrade to level "+(level.intValue()+1))));inv.setItem(11,item(Material.DIAMOND,ChatColor.AQUA+"Pay with diamonds",ChatColor.GRAY+purchases.price(r.getUniqueId(),effectId,"diamond")));inv.setItem(13,item(Material.EXPERIENCE_BOTTLE,ChatColor.GREEN+"Pay with EXP levels",ChatColor.GRAY+purchases.price(r.getUniqueId(),effectId,"exp")));inv.setItem(15,item(Material.GOLD_INGOT,ChatColor.GOLD+"Pay with Vault money",ChatColor.GRAY+purchases.price(r.getUniqueId(),effectId,"money"),ChatColor.GRAY+"Requires Vault and an economy provider"));inv.setItem(22,item(Material.ARROW,ChatColor.YELLOW+"Back"));}
    @EventHandler public void click(InventoryClickEvent e){Inventory top=e.getView().getTopInventory();if(!(top.getHolder() instanceof ClassicGuiHolder))return;e.setCancelled(true);if(!(e.getWhoClicked() instanceof Player)||e.getRawSlot()<0||e.getRawSlot()>=top.getSize())return;Player p=(Player)e.getWhoClicked();ClassicGuiHolder h=(ClassicGuiHolder)top.getHolder();ClassicBeaconRecord r=state.find(h.getLocation());if(r==null){p.closeInventory();return;}if(ownerOnlyInteract&&!authorized(p,r)){p.closeInventory();return;}int slot=e.getRawSlot();if(h.getMenu()==ClassicGuiHolder.Menu.MAIN){if(slot==20)open(p,r,ClassicGuiHolder.Menu.EFFECTS,null);else if(slot==22){mutations.toggleRange(h.getLocation());open(p,state.find(h.getLocation()),ClassicGuiHolder.Menu.MAIN,null);}else if(slot==24)open(p,r,ClassicGuiHolder.Menu.BEAM_STYLES,null);else if(slot==49)p.closeInventory();return;}if(h.getMenu()==ClassicGuiHolder.Menu.PAYMENT){if(slot==22){open(p,r,ClassicGuiHolder.Menu.EFFECTS,null);return;}String option=slot==11?"diamond":slot==13?"exp":slot==15?"money":null;if(option!=null){ClassicPurchaseService.Result result=purchases.purchase(p,r.getUniqueId(),h.getEffectId(),option);p.sendMessage(message(result));open(p,state.find(h.getLocation()),result==ClassicPurchaseService.Result.COMMITTED?ClassicGuiHolder.Menu.EFFECTS:ClassicGuiHolder.Menu.PAYMENT,result==ClassicPurchaseService.Result.COMMITTED?null:h.getEffectId());}return;}if(slot==49){open(p,r,ClassicGuiHolder.Menu.MAIN,null);return;}if(h.getMenu()==ClassicGuiHolder.Menu.BEAM_STYLES){int index=index(slot);if(index>=0&&index<beamIds.size()&&mutations.selectBeam(h.getLocation(),beamIds.get(index))==ClassicGuiMutationService.Result.COMMITTED)open(p,state.find(h.getLocation()),ClassicGuiHolder.Menu.BEAM_STYLES,null);return;}if(h.getMenu()==ClassicGuiHolder.Menu.EFFECTS){int index=index(slot);List<ClassicEffectCatalog.Definition> defs=effects.getDefinitions();if(index<0||index>=defs.size())return;ClassicEffectCatalog.Definition d=defs.get(index);Integer level=r.getEffects().get(d.getId());if(e.isRightClick()&&(level==null||level.intValue()<d.getMaxLevel()))open(p,r,ClassicGuiHolder.Menu.PAYMENT,d.getId());else if(level!=null&&mutations.toggleEffect(h.getLocation(),d.getId(),true)==ClassicGuiMutationService.Result.COMMITTED)open(p,state.find(h.getLocation()),ClassicGuiHolder.Menu.EFFECTS,null);}}
    @EventHandler public void drag(InventoryDragEvent e){if(e.getView().getTopInventory().getHolder() instanceof ClassicGuiHolder)e.setCancelled(true);}
    private static String message(ClassicPurchaseService.Result r){if(r==ClassicPurchaseService.Result.COMMITTED)return ChatColor.GREEN+"Effect purchase committed.";if(r==ClassicPurchaseService.Result.INSUFFICIENT_FUNDS)return ChatColor.RED+"Insufficient funds.";if(r==ClassicPurchaseService.Result.ECONOMY_UNAVAILABLE)return ChatColor.RED+"Vault economy is unavailable.";if(r==ClassicPurchaseService.Result.PERSISTENCE_FAILED_REFUNDED)return ChatColor.RED+"Purchase failed; payment was refunded.";return ChatColor.RED+"Purchase failed safely: "+r.name();}
    private static boolean authorized(Player p,ClassicBeaconRecord r){UUID id=p.getUniqueId();return p.hasPermission("NexusBeacon.admin")||id.equals(r.getOwner())||r.getTrusted().contains(id);}
    private static int index(int slot){for(int i=0;i<CONTENT.length;i++)if(CONTENT[i]==slot)return i;return -1;}
    static boolean opensGui(Action action){return action==Action.RIGHT_CLICK_BLOCK;} static boolean returnsPortable(GameMode mode,boolean configuredCreativeNoDupe){return true;}
    private static ItemStack item(Material material,String name,String...lore){ItemStack i=new ItemStack(material);ItemMeta meta=i.getItemMeta();meta.setDisplayName(name);List<String> lines=new ArrayList<String>();for(String line:lore)lines.add(line);meta.setLore(lines);i.setItemMeta(meta);return i;}
    private static String title(ClassicGuiHolder.Menu menu){if(menu==ClassicGuiHolder.Menu.EFFECTS)return ChatColor.DARK_GRAY+"NexusBeacon Effects";if(menu==ClassicGuiHolder.Menu.BEAM_STYLES)return ChatColor.DARK_GRAY+"NexusBeacon Beam";if(menu==ClassicGuiHolder.Menu.PAYMENT)return ChatColor.DARK_GRAY+"NexusBeacon Payment";return ChatColor.DARK_GRAY+"NexusBeacon";}
    private static ClassicBeaconLocation loc(Block b){return new ClassicBeaconLocation(b.getWorld().getName(),b.getX(),b.getY(),b.getZ());}
}
