package cl.dynasty.nexusbeacon.platform.classic;
import java.util.ArrayList; import java.util.Collection; import java.util.Collections; import java.util.Map; import java.util.TreeMap; import java.util.UUID;
public final class ClassicApplicationState {
    public enum Status { NEW, READY_EMPTY, READY, FAILED, CLOSED }
    private final ClassicBeaconStorage storage; private Map<ClassicBeaconLocation,ClassicBeaconRecord> records=Collections.emptyMap(); private Status status=Status.NEW;
    public ClassicApplicationState(ClassicBeaconStorage storage){if(storage==null)throw new NullPointerException("storage");this.storage=storage;}
    public synchronized ClassicStorageLoad initialize(){if(status!=Status.NEW)throw new IllegalStateException("Already initialized"); ClassicStorageLoad load=storage.load(); if(!load.isSuccessful()){status=Status.FAILED;return load;} TreeMap<ClassicBeaconLocation,ClassicBeaconRecord> next=new TreeMap<ClassicBeaconLocation,ClassicBeaconRecord>(); java.util.HashSet<UUID> ids=new java.util.HashSet<UUID>(); for(ClassicBeaconRecord r:load.getRecords())if(next.put(r.getLocation(),r)!=null||!ids.add(r.getUniqueId())){status=Status.FAILED;return ClassicStorageLoad.failure(ClassicStorageLoad.Status.CORRUPT,"Duplicate record");} records=Collections.unmodifiableMap(next);status=records.isEmpty()?Status.READY_EMPTY:Status.READY;return load;}
    public synchronized ClassicBeaconRecord find(ClassicBeaconLocation l){ready();return records.get(l);} public synchronized int size(){ready();return records.size();} public synchronized Collection<ClassicBeaconRecord> snapshot(){ready();return new ArrayList<ClassicBeaconRecord>(records.values());}
    public synchronized ClassicBeaconRecord findByUniqueId(UUID id){ready();if(id==null)return null;for(ClassicBeaconRecord record:records.values())if(id.equals(record.getUniqueId()))return record;return null;}
    public synchronized boolean isAuthoritative(ClassicBeaconRecord record){ready();return record!=null&&record.equals(records.get(record.getLocation()));}
    public synchronized boolean insert(ClassicBeaconRecord r){ready();if(records.containsKey(r.getLocation()))return false;for(ClassicBeaconRecord x:records.values())if(x.getUniqueId().equals(r.getUniqueId()))return false;TreeMap<ClassicBeaconLocation,ClassicBeaconRecord> n=new TreeMap<ClassicBeaconLocation,ClassicBeaconRecord>(records);n.put(r.getLocation(),r);commit(n);return true;}
    public synchronized boolean update(ClassicBeaconRecord r){ready();if(!records.containsKey(r.getLocation()))return false;TreeMap<ClassicBeaconLocation,ClassicBeaconRecord> n=new TreeMap<ClassicBeaconLocation,ClassicBeaconRecord>(records);n.put(r.getLocation(),r);commit(n);return true;}
    public synchronized ClassicBeaconRecord remove(ClassicBeaconLocation l){ready();ClassicBeaconRecord old=records.get(l);if(old==null)return null;TreeMap<ClassicBeaconLocation,ClassicBeaconRecord> n=new TreeMap<ClassicBeaconLocation,ClassicBeaconRecord>(records);n.remove(l);commit(n);return old;}
    public synchronized void close(){if(status==Status.CLOSED)return;storage.close();records=Collections.emptyMap();status=Status.CLOSED;} public Status getStatus(){return status;}
    private void commit(TreeMap<ClassicBeaconLocation,ClassicBeaconRecord> n){storage.store(n.values());records=Collections.unmodifiableMap(n);status=n.isEmpty()?Status.READY_EMPTY:Status.READY;} private void ready(){if(status!=Status.READY&&status!=Status.READY_EMPTY)throw new IllegalStateException("State unavailable: "+status);}
}
